### PR TITLE
Remove extra plugin title in breadcrumbs

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by cmckni3** [comment]
@owen2345 Any possibility of looking at open Pull Requests? #5 #8

**Comment by owen2345** [comment]
Why delete plugin title?

**Comment by cmckni3** [comment]
It shows up twice in the breadcrumbs. I believe it is added somewhere else but I can't find where.

**Comment by owen2345** [comment]
Each plugin will need to add their breadcrumbs with:
 admin_breadcrumb_add("My breadcrumb title", "the_url (optional)")

**Comment by cmckni3** [comment]
>  Each plugin will need to add their breadcrumbs with:
>  admin_breadcrumb_add("My breadcrumb title", "the_url (optional)")

I'm not opposed to having the plugin call `admin_breadcrumb_add`. It would allow finer controller.

On the other hand, we could modify the breadcrumb instance variable, `@_admin_breadcrumb`, to change the breadcrumbs. However, I don't like this since it requires knowledge of the implementation and structure of the instance variable.

**Pull request merged**
