### PR TITLE
Moduler

### PR DESCRIPTION
**Pull request by raulanatol**
Clean elfinder
Merge with angular-filemanager

### CODE REVIEW

**Comment by owen2345** [comment]
Hey @raulanatol ,
I merged your changes!

**Comment by raulanatol** [comment]
Thx @owen2345.
I will be testing this branch.

**Comment by owen2345** [comment]
Hey  @raulanatol  I comment you that select feature inage in posts is not working "javascript errors" . Also is there posible to see mode thumbnails?, right now is a little complicated to select your image.
Regards,

**Comment by raulanatol** [comment]
Hi @owen2345.

- feature image in post: Don't worry. I got this.
- thumbnails mode: I have in mind but angular-filemanager don't have this feature. Maybe we could be created this feature.

Regards.

**Comment by rh0delta** [comment]
Hello all,

I recently found this to be quite the useful CMS for the new blog feature on my company's website. I was just wondering when the public release for S3 integration will be available?

Regards.

**Pull request merged**
