### PR TITLE
fix PostgreSQL name

### PR DESCRIPTION
**Pull request by Rodrifer**

### CODE REVIEW

**Comment by cmckni3** [comment]
Requirements is also misspelled

**Comment by cmckni3** [comment]
I would recommend moving the Requirements section to the top of the README.

I like using shields.io badges under the name as well.

**Comment by owen2345** [comment]
Done!

**Comment by cmckni3** [comment]
@owen2345 This can be closed, correct?

**Comment by owen2345** [comment]
Merged Manually

**Pull request closed without merging**
