### PR TITLE
Permit to change post author

### PR DESCRIPTION
**Pull request by gcrofils**
I wanted to add a feature to permit to change post author and try to do it in the CamaleonCMS way.

Note: only users who can edit others are allowed to change author.

### CODE REVIEW

**Comment by owen2345** [comment]
Hi @gcrofils 
could you please send me a screenshot of the result?
Regards,

**Comment by gcrofils** [comment]
Sure. Below with Visibility Posts activated.
permit to change post author

**Comment by gcrofils** [comment]
additional screen copy. This author has a contributor role. Therefore she has no right to change the author.

default author

**Comment by gcrofils** [comment]
Last commit includes the fix for #376

**Pull request merged**
