### PR TITLE
Allow latest TinyMCE

### LINKED ISSUE #929: TinyMCE not compiling with Sprockets 4
For some reason, TinyMCE assets aren't being compiled when using Camaleon with Sprockets 4. I haven't been able to track down why this happens. TinyMCE appears to be correctly required by [this line](https://github.com/owen2345/camaleon-cms/blob/504cebf20a29439ae1a7338c2973ed564ea805ad/app/assets/javascripts/camaleon_cms/admin/admin-manifest.js#L45), and eveything else required in that manifest seems to work fine. I'm not sure whether the problem is in Camaleon, tinymce-rails, or sprockets.

The only workaround I've found (besides downgrading Sprockets) is:
```ruby
# config/environments/production.rb

config.assets.compile = true
```

This is definitely a workaround and not a solution, though, since this causes the files to be served without the fingerprinting used for CDN cache expiration.

### PR DESCRIPTION
**Pull request by brian-kephart**
Fixes #929. TinyMCE was not compiling with Sprockets 4 because of an [issue in the tinymce-rails gem](https://github.com/spohlenz/tinymce-rails/issues/264).

The current gemspec locks to version 4 of tinymce-rails, so to get the fix we need to bump to version 5, which required a few other changes.

There are a few deprecation warnings with the new version. These have not been addressed. (see image)
Screen Shot 2020-01-05 at 10 45 41 PM

Tests pass, except where affected by #930. For a build that includes the patch for that issue submitted in #931, see [here](https://travis-ci.com/brian-kephart/camaleon-cms/builds/143191248). That build includes one failure as the result of a segmentation fault in a version of the sassc-rails gem, unrelated to this issue.

### CODE REVIEW

**Comment by owen2345** [comment]
Hi @brian-kephart 
tinymce-rails was updated 6 hours ago. Could you pls test it again?

**Comment by brian-kephart** [comment]
@owen2345 thanks for the fast response. This PR was submitted after tinymce-rails was already updated, so the build already includes the new version. The test failures are the result of an update to Rack as described in #930 and have nothing to do with this PR. I can't make those pass without either merging that PR or locking the version of Rack in the Gemfile.

I made a branch on my fork that includes both PRs, and you can see the build results in the last link in my message above. If you merge #931 or another fix for #930, I'll merge the changes into this branch. That should trigger a passing build. Please let me know if there's anything else I can do.

**Comment by owen2345** [comment]
Hi @brian-kephart 
I was working in the fix and I have this PR: https://github.com/owen2345/camaleon-cms/pull/934
I tested in local with rails 4x, 5x, 6x, ruby 3.3, 3.5, 3.6 and sprokects 3x / 4.0 and all worked well. Could you pls test it with your application?
Cheers!

**Comment by brian-kephart** [comment]
My tests pass with the new version, but production is broken. I thought it might be due to CDN caching since you change the TinyMCE installation option from `:compile` to `:copy` so those assets are no longer versioned (and I had the later version of TinyMCE installed previously), but even after invalidating my CDN assets the problems remain.

Screen Shot 2020-01-08 at 8 37 17 PM
Screen Shot 2020-01-08 at 8 37 24 PM
Screen Shot 2020-01-08 at 8 38 01 PM

**Comment by brian-kephart** [comment]
I figured out why my app doesn't work with the current version. I deploy to Heroku. On deploy, Heroku runs `rake assets:precompile` followed by `rake assets:clean`. With the TinyMCE installation option set to `:copy` instead of `compile`, the TinyMCE assets don't get versioned during precompilation, so running `rake assets:clean` deletes them. This is in addition to the CDN caching problem referred to in my previous comment.

So, the current version doesn't work on Heroku and has issues with CDNs. We should seek a solution that leaves that option set to `:compile`. I see three possibilities for this:

1. Use the latest TinyMCE. There are some breaking changes within TinyMCE, but if these are handled in the Camaleon update there might not be any breaking changes experienced by Camaleon users. For example, I have a codesample plugin enabled that required no changes to work with this PR.
2. Try to get tinymce-rails maintainers to backport the Sprockets 4 fix from the 5.x branch to the 4.x branch and release a version.
3. Try and make the 4.x version compile in another way. [Here's the commit introducing Sprockets 4 support in version 5.x](https://github.com/spohlenz/tinymce-rails/commit/f305e3b6780a5237a544c0ddb84be32defcbd191).

Any thoughts?

**Comment by owen2345** [comment]
Hi @brian-kephart 
thanks for testing! I think the option #2 is more confortable if we clone the old version, make changes for sprockes 4 and use it in the CMS. What do you think?
Note: If we use tinymce new version, will break several thinks because they changed several things on how to use tinymce.
Regards!

**Comment by brian-kephart** [comment]
@owen2345 I think that's reasonable. The new TinyMCE seems to work fine for a basic Camaleon installation, but anyone hooking into it with their own scripts could see problems. I'm submitting a request to tinymce-rails to backport to the 4.x branch, so we'll see what the maintainer says.

**Comment by brian-kephart** [comment]
I went ahead and merged the recent CMS changes into this branch for testing, in case we ever revisit tinymce-rails 5. All tests appear to pass, except for a segfault in the sassc gem when using Ruby 2.5.

**Comment by brian-kephart** [comment]
Actually, [the tests all pass on my CI](https://travis-ci.com/brian-kephart/camaleon-cms/builds/144406544). I'm not sure why the Ruby 2.5 job segfaults here.

**Comment by owen2345** [comment]
@brian-kephart pls try again, guys from tinymce-rails added support for sprockets 4.

**Comment by brian-kephart** [comment]
Yes, that works with the new version. Sorry for the delays, I was unable to verify the fix until now because of a different bug with compiling assets in my app.

**Pull request closed without merging**
