### PR TITLE
TinyMCE version 5

### PR DESCRIPTION
**Pull request by brian-kephart**
This PR completes the upgrade of TinyMCE to v5, replacing #1035. It has been rebased on the v3 branch. One last consideration is whether the TinyMCE assets should be copied or compiled. We've switched it a couple of times. This PR chooses the compile option, but only because I did that for some reason when I first tried version 5 in 2020. It can be changed if needed.

For the next upgrade to v6, the tricky part is that the jQuery wrapper was removed from the gem, so we most likely have to change a bunch of code. We had discussed removing jQuery entirely and re-writing the frontend, so I'd like to hear ideas about that before diving into the next step.

### CODE REVIEW

**Review by texpert — APPROVED** [review]
LGTM

As for the assets, is there any reason for compiling them (minification, additional browsers support, etc.)? If no, then copying should be faster, reducing the deployment time.

**Review by owen2345 — APPROVED** [review]
LG2M

**Comment by brian-kephart** [comment]
@texpert I don't have any of the concerns you listed. I just want the assets to get digested properly so they can be properly expired if assets are served through a caching CDN.

**Comment by brian-kephart** [comment]
Also, I'm finding that the tinyMCE assets are not available in the dev environment using the `:copy` method unless assets are first precompiled.

**Comment by brian-kephart** [comment]
Added a commit to fix #1038.

**Pull request merged**
