### PR TITLE
Added Gemfile.lock to gitignore file

### PR DESCRIPTION
**Pull request by mazharoddin**
I added Gemfile.lock back to gitignore file, because of Gemfile.lock file I am unable to use rails5.0 though I have rails5.0 installed on my system.

### CODE REVIEW

**Comment by p-decoraid** [comment]
Gemfile.lock should only be used when developing camaleon-cms itself. How is it affecting your project?

**Comment by p-decoraid** [comment]
Not to mention, there is still a Gemfile.lock in the repo...

**Comment by mazharoddin** [comment]
Hi, I am getting this issue when I am using cloned copy of camaleon_cms using my Gemfile as below.
```
gem 'camaleon_cms', '2.3.6', path: 'vendor/plugins/camaleon-cms'
```

**Comment by p-decoraid** [comment]
What is the issue?

**Pull request merged**
