### PR TITLE
fix syntax api_controller for Heroku

### PR DESCRIPTION
**Pull request by Silvaire**
Error Stack on heroku:

[3] ! Unable to load application: SyntaxError: /app/vendor/bundle/ruby/2.1.0/gems/camaleon_cms-1.0.8/app/controllers/api/api_controller.rb:10: syntax error, unexpected ':', expecting =>
        'userMessage': user_message,
                      ^
/app/vendor/bundle/ruby/2.1.0/gems/camaleon_cms-1.0.8/app/controllers/api/api_controller.rb:11: syntax error, unexpected ':', expecting :: or '[' or '.'
    'internalMessage': internal_message,
                      ^
/app/vendor/bundle/ruby/2.1.0/gems/camaleon_cms-1.0.8/app/controllers/api/api_controller.rb:12: syntax error, unexpected ':', expecting :: or '[' or '.'
    'code': code
           ^
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': /app/vendor/bundle/ruby/2.1.0/gems/camaleon_cms-1.0.8/app/controllers/api/api_controller.rb:10: syntax error, unexpected ':', expecting => (SyntaxError)
        'userMessage': user_message,
                      ^
/app/vendor/bundle/ruby/2.1.0/gems/camaleon_cms-1.0.8/app/controllers/api/api_controller.rb:11: syntax error, unexpected ':', expecting :: or '[' or '.'
    'internalMessage': internal_message,
                      ^
/app/vendor/bundle/ruby/2.1.0/gems/camaleon_cms-1.0.8/app/controllers/api/api_controller.rb:12: syntax error, unexpected ':', expecting :: or '[' or '.'
    'code': code

### CODE REVIEW

**Comment by cmckni3** [comment]
This PR is unnecessary because this just converts to using Ruby 1.8 syntax. I fixed this in an earlier commit. You should update camaleon and deploy to heroku.

I fixed this in #171. See the [commit](https://github.com/cmckni3/camaleon-cms/commit/193a9a16746597c212e375041a524f44e6943765) for more information.

**Comment by Silvaire** [comment]
Alright, thank you for the info and sorry for the useless PR. I changed my Gemfile to point to https://github.com/owen2345/camaleon-cms and it works now. Because when fetching straight from rubygems, I still get this in ```app/controllers/api/api_controller.rb```:

``` ruby
class Api::ApiController < CamaleonController
  #before_action -> { doorkeeper_authorize! :client }

  def account
    render json: current_user
  end

  def render_json_error(internal_message = 'Unexpected error', code = 100, status = 404, user_message = 'Unexpected error')
    error = {
        'userMessage': user_message,
    'internalMessage': internal_message,
    'code': code
    }
    render :json => error, :status => status
  end

  def render_json_ok(message = 'Success', status = 200, more_info = {})
    msg = {
        message: message,
        more_info: more_info
    }
    render :json => msg, :status => status
  end

end
```

**Comment by cmckni3** [comment]
Yeah for now you need to point to master or a commit on master because the ruby gems version is broken.

@owen2345 can you yank that release on ruby gems and add a new, good release?

**Comment by owen2345** [comment]
Hi @cmckni3 right now I will do it.

**Comment by owen2345** [comment]
Done!
I published the new gem version "1.0.9".

**Comment by cmckni3** [comment]
:+1: 

Can you yank 1.0.8?

http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem

**Comment by Silvaire** [comment]
Actually, this PR also removed some (what I assume is debug) code in the `sitemap` method of `app/controllers/concerns/frontend_concern.rb`.

Could this be removed from the main repo? `/sitemap.xml` currently gives a 500, with `undefined local variable or method 'a' for #<FrontendController>`

**Comment by cmckni3** [comment]
So it does.

Opened #199

**Comment by cmckni3** [comment]
Fixed by #199 

/ping @owen2345

**Comment by cmckni3** [comment]
This should have been just closed but not a big deal.

**Pull request merged**
