### PR TITLE
Fix missing gems

### PR DESCRIPTION
**Pull request by cmckni3**
`Could not find mini_magick-4.3.0 in any of the sources`

### CODE REVIEW

**Comment by cmckni3** [comment]
Deleted lib/Gemfile as well.

**Comment by owen2345** [comment]
That is not possible, I tried several ways that without sucsess.
I got a lot of errors with gem dependencies, I think that rails is not recognizing the gems because this is a non mountable engine and not just a gem.
Try to install the cms using the path to your local folder in your gemfile.

**Comment by cmckni3** [comment]
That makes sense.

Is there any way to make it a mountable engine? The require in the `Gemfile` is really weird to me.

**Comment by owen2345** [comment]
I tried, but it is too complicated.

**Comment by cmckni3** [comment]
My branch appears to work for me.

Was there something specific that didn't work?

**Comment by cmckni3** [comment]
I see the issue now. I had to upload my plugin_routes file.

**Comment by owen2345** [comment]
please let me know if you can solve the problem.

**Comment by cmckni3** [comment]
Fixed

**Comment by cmckni3** [comment]
Is nokogiri being used?

**Comment by cmckni3** [comment]
@owen2345

**Comment by owen2345** [comment]
It is not longer used.
It was used by admin menus, but it was rebuilt without nokogiri.

**Comment by cmckni3** [comment]
Cool. I removed it.

Can you check this out now?

**Pull request merged**
