### PR TITLE
add codesample plugin/toolbar to TinyMCE

### PR DESCRIPTION
**Pull request by brian-kephart**
This PR adds support for [TinyMCE's codesample plugin](https://www.tinymce.com/docs/plugins/codesample/), allowing for formatted blocks of code to be displayed. The plugin and toolbar are both necessary.

For full formatting functionality, PrismJS needs to be installed as detailed [here](http://prismjs.com/#basic-usage). However, not having it installed won't break anything. It will still create tags that can be styled using CSS.

Screenshot without PrismJS (no custom styling applied):
screen shot 2018-03-28 at 11 03 38 pm

Screenshot with PrismJS:
screen shot 2018-03-28 at 11 04 27 pm

I added the JS & CSS files to the asset pipeline. Example use:
```erb
<%= stylesheet_link_tag 'camaleon_cms/prismjs/prism' %>
<%= javascript_include_tag 'camaleon_cms/prism' %>
```

PrismJS has various themes that can be used by swapping the CSS file. The available files are:
```
camaleon_cms/prismjs/prism
camaleon_cms/prismjs/prism-dark
camaleon_cms/prismjs/prism-funky
camaleon_cms/prismjs/prism-okaidia
camaleon_cms/prismjs/prism-twilight
camaleon_cms/prismjs/prism-coy
camaleon_cms/prismjs/prism-solarizedlight
camaleon_cms/prismjs/prism-tomorrow
```

### CODE REVIEW

**Comment by brian-kephart** [comment]
I should clarify, using PrismJS is only used for the frontend formatting, and only if someone actually uses codesample blocks in their content. PrismJS is not used in the backend. In other words, this shouldn't break anything.

If this PR is accepted, though, I think the documentation should be updated to show how to include PrismJS files in the frontend as shown in my comment above. I didn't put anything in the README because it seems to belong [here](http://camaleon.tuzitio.com/docs.html) instead, but I'd be happy to write something up if it would help.

**Comment by owen2345** [comment]
Hi @brian-kephart I am sorry, but this should be a new camaleon cms plugin like: https://github.com/owen2345/Camaleon-Tinymce-Templates
To be installed by users who need this feature.

**Comment by brian-kephart** [comment]
Thanks, I've gotten it working. Could the documentation be updated to refer to that plugin? My first thought was to write a plugin to do this, but I couldn't figure out how without that to guide me.

**Comment by owen2345** [comment]
@brian-kephart please use this manual: http://camaleon.tuzitio.com/documentation/category/40758-modules/plugins-3.html
- include your javascript libraries using before_admin_load hook.
- add your tinymce settings and callbacks using tinymce_global_settings like here: https://github.com/owen2345/Camaleon-Tinymce-Templates/blob/master/app/assets/javascripts/plugins/cama_tinymce_template/main.js#L3
that is all.
Cheers!

**Comment by brian-kephart** [comment]
Thanks @owen2345, I appreciate the response. I think I wan't clear about my documentation request, though. I searched the documentation at http://camaleon.tuzitio.com/documentation before filing this PR, and I did not find anything about adding a plugin to tinyMCE. Once you posted the link to  https://github.com/owen2345/Camaleon-Tinymce-Templates then everything became clear. My request is to add a link to that plugin to the documentation so it's easier to find.

Thanks again for your help!

**Pull request closed without merging**
