### PR TITLE
Swagger docs

### PR DESCRIPTION
**Pull request by raulanatol**
I have added the swagger-docs gem to permit auto documentation the api methods.

To regenerate the documentation: 
```
rake swagger:docs
```

The documentation controller is: .../admin/doc

More information: 
- https://github.com/richhollis/swagger-docs
- http://swagger.io/

### CODE REVIEW

**Comment by cmckni3** [comment]
This idea is pretty neat. It follows what strongloop (node.js framework) does out of the box.

I wouldn't put the documentation in the repo though. The swagger README even advises against this. They advise to either run `swagger:docs` on deploy or integrate it into `assets:precompile`.

**Comment by raulanatol** [comment]
I have added the precompile step. Thanks @cmckni3 ;)

**Comment by cmckni3** [comment]
Sweet

The previously generated swagger docs and assets weren't removed though.

**Comment by cmckni3** [comment]
Is the `public/swagger-ui` folder supposed to be in the gem?

**Comment by raulanatol** [comment]
Yes @cmckni3.
The public/swagger-ui folder is the "front-end" of the documentation. Not is auto-generated.

**Comment by cmckni3** [comment]
Ok, that makes sense

**Pull request merged**
