### PR TITLE
757 aws media does not scale

### PR DESCRIPTION
**Pull request by tostasqb**
Hi @owen2345. this is quite a massive Pull Request.
There are many changes on how the media gallery is resolved so bear in mind all good intentions :) I tried to keep all things compatible but I'll need more people/projects to be tested on.
Is not meant to be accepted right away but further discussed, as it is a possible solution for issue #757.

To get started run a`rake db:migrate` and, in case you're connected to aws, a `rake camaleon_cms:sync_db_and_s3_files` to update the new `cama_media` table with all that's on the aws bucket.

~~Paging is still missing on the media gallery/browser~~. Overall it meant a massive change on responsiveness of that area as far as I can tell and been testing.

Let me hear your thoughts and comments as well as the rest of the guys wanting to contribute.

### CODE REVIEW

**Comment by owen2345** [comment]
Hi @tostasqb this is great! Let me review and make some tests this week before merging into master branch...

**Comment by owen2345** [comment]
Hi @tostasqb sorry for my delay but I was working in this pull request, unfortunately there were many errors and I worked from scratch using some code of your pull request. Please review and let me know if it works well for you too before to release another version.

**Comment by tostasqb** [comment]
No problem @owen2345. But in which branch are you working on this?

**Comment by owen2345** [comment]
I pushed to master branch because we tested it for a week and worked well. Cheers!

**Pull request closed without merging**
