### PR TITLE
Remove btn-preview Because it's not working

### PR DESCRIPTION
**Pull request by Abd-El-Rahman-HSN**

### CODE REVIEW

**Comment by superchell** [comment]
this button is 100% working! It may not work, only if you customized the post type routes (http://camaleon.tuzitio.com/documentation/category/139779-faqs/customize-post-type-routes.html). And in general you send very dirty PR, for example, why include in the commit server.pid? Or why do you insert useless whitespaces? Be careful, please.

**Comment by Abd-El-Rahman-HSN** [comment]
image

this button is Not working!

**Comment by superchell** [comment]
@Abd-El-Rahman-HSN button is working, remove this PR, please. Proof in my project development 
jlgocbf

**Comment by Abd-El-Rahman-HSN** [comment]
How to delete this button on project me

**Comment by superchell** [comment]
you may override admin template in your project - just copy needed template in this folder https://i.imgur.com/gHrEVZq.png and edit that

**Comment by Abd-El-Rahman-HSN** [comment]
Explain more I don't understand

**Pull request closed without merging**
