### PR TITLE
Feature/improve app settings for rails7

### PR DESCRIPTION
**Pull request by owen2345**
- [x] feat: ignore default themes assets, views, helpers, and so on (since default themes are copied to the app during the installation, then default themes from the gem should no longer be taken into account)
- [x] chore: improve readme for rails 7

### CODE REVIEW

**Review by texpert — APPROVED** [review]
LGTM

Regarding the failing tests on Rails 7 and higher, @brian-kephart has commented here https://github.com/DatabaseCleaner/database_cleaner/issues/693

But I think it is better just to get rid of the DatabaseCleaner, favouring the `use_transactional_fixture` Rails setting. See, for example, https://github.com/jrochkind/attr_json/pull/153

**Comment by brian-kephart** [comment]
@owen2345 LGTM.

@texpert The reason for not using transactional features is that capybara runs the browser in a different thread from the app server, so it cannot see the data from uncommitted transactions. If you look in the spec_helper.rb it specifically only uses truncation for browser tests, and uses transactions for other types. So it's hard to remove DatabaseCleaner without rewriting the tests.

**Review by brian-kephart — APPROVED** [review]

**Comment by texpert** [comment]
https://github.com/owen2345/camaleon-cms/pull/1028 has been merged, so rebasing this PR on fresh master branch should make the tests pass.

**Comment by texpert** [comment]
DB failures are gone.

**Comment by owen2345** [comment]
> DB failures are gone.

Checking… Thanks @texpert

**Pull request merged**
