### PR TITLE
Allow email domains up to 10 characters in the contact form plugin

### PR DESCRIPTION
**Pull request by flaranda**
For new email domains terminations (example: .digital)

### CODE REVIEW

**Comment by flaranda** [comment]
For new email domains terminations (example: .digital)

**Comment by cmckni3** [comment]
I think you could just do a minimum length of 2, `{2,}`.

If it were up to me, I would just do a simple check with the regex `/@/`

**Comment by owen2345** [comment]
yes, you are right Chris!

**Comment by owen2345** [comment]
What about?:
"myemail@myhost.myextension".match(/\S+@\S+\.\S+/)

**Comment by cmckni3** [comment]
Close, but you have the `.` metacharacter which means "match anything". You want the literal `.`, so, you need `\.`

**Comment by cmckni3** [comment]
Otherwise, that would work.

**Comment by cmckni3** [comment]
I would have to go look at the rfc for email address but I'm sure you can have special characters in an email account name which would be accounted for in your regex.

N.B. `\S` is short for `[^\f\n\r\t\v\u00A0\u2028\u2029]`. `^` meaning negation since it is in character group.

**Comment by owen2345** [comment]
mmm the easier is only verify for /@/ for now!

**Comment by cmckni3** [comment]
Exactly, haha

**Pull request merged**
