### PR TITLE
Update supported Ruby/Rails

### PR DESCRIPTION
**Pull request by brian-kephart**
This is the usual stuff.

EOL versions removed:
- Ruby 2.7
- Rails 6.0

Newer versions added to the build matrix:
- Ruby 3.2
- Rails 7.1

No changes were necessary for the new support, except to placate RuboCop after updating the target Ruby version.

### CODE REVIEW

**Review by texpert — APPROVED** [review]
LGTM

I'm a little bit reluctant of dropping support of Ruby 2.7 - think there may be several apps using it yet.

**Comment by brian-kephart** [comment]
I found a bug that affected low-level caching of decorator classes. This bug only happened when loading version 7.1 defaults, so I had to reproduce that condition in the dummy app in order to add a test for it. This made me think that the dummy app should load the defaults for whatever version of Rails is being tested against, so I added that. Using the per-version Rails defaults caused another couple of test failure that had to be fixed.

All is working now though, and the tests are now better at checking against evolving Rails defaults.

**Comment by brian-kephart** [comment]
@texpert We can support 2.7 if you want to. I thought we had decided earlier to drop support for versions when they go EOL, and that version went EOL months ago so I removed it. Supporting it wasn't causing any trouble, though.

I always figure that if someone isn't updating Ruby, they're probably not updating their gems either, but people often surprise me. 🙃

**Review by texpert — APPROVED** [review]
LGTM, great work!

**Comment by texpert** [comment]
> @texpert We can support 2.7 if you want to. I thought we had decided earlier to drop support for versions when they go EOL, and that version went EOL months ago so I removed it. Supporting it wasn't causing any trouble, though.
> 
> I always figure that if someone isn't updating Ruby, they're probably not updating their gems either, but people often surprise me. 🙃

I'd propose to cut a 2.7.5 release before merging this branch, stating in the changelog that it is the last version with Ruby 2.7 support. We have the JS fixes in `master`, the SSRF mitigation, and it would be good to make a fixed final release for 2.7

And then to merge this PR and cut a new 2.8.0 release.

**Pull request merged**
