### PR TITLE
using content slug instead of id to prevent conflict between multiple sites

### PR DESCRIPTION
**Pull request by phlcastro**
this fix is related to this issue: https://github.com/owen2345/camaleon-cms/issues/655

### CODE REVIEW

**Comment by haffla** [comment]
I see your problem but I don't understand your fix. Well I understand it but I don't know why it solves your problem. Both `slug` and `id` of the post_type are unique for one site, so both should work.

I think the reason why only one of your sites work (always the one defined last?) lies somewhere around [config/routes/frontend.rb#L76](https://github.com/owen2345/camaleon-cms/blob/master/config/routes/frontend.rb#L76).

But well if this fixes the problem, OK.

**Comment by phlcastro** [comment]
@haffla this line you mentioned is responsible to create the routes dynamically. it will load all sites and their post_types (and set `post_type_id`). the problem is that this will generate two identical routes (in case you have two sites using the same slug. ie.: `/.post`) and set the `post_type_id` twice with different values.

when user try to access `/post`, Rails will reach the first route and this may not have the correct `post_type_id`.

its easy to understand if you setup a local env and tried it by yourself.

**Comment by haffla** [comment]
Yeap, it makes sense :+1:

**Comment by phlcastro** [comment]
hi @owen2345 any thoughts on that?

**Comment by owen2345** [comment]
I agree with you guys!

**Pull request merged**
