### PR TITLE
Add media search

### PR DESCRIPTION
**Pull request by cmckni3**
WIP: Adds media search

The sidebar isn't showing on the search page

### CODE REVIEW

**Comment by cmckni3** [comment]
Any ideas why the sidebar doesn't show on the search page, @owen2345? It's empty.

**Comment by owen2345** [comment]
@cmckni3 could you please send me a screenshot?

**Comment by cmckni3** [comment]
Uhhh this wasn't ready to merge. Should be ok though if you fix the sidebar.

**Comment by cmckni3** [comment]
Any ideas @owen2345?

**Comment by cmckni3** [comment]
Seems like some global state somewhere is messed up.

**Comment by owen2345** [comment]
@cmckni3 there is a method to initialize the sidebar menus:
admin_menus_add_commons() in CamaleonCms::AdminController
please check line 85

**Comment by cmckni3** [comment]
I shouldn't have to call that method....

**Comment by owen2345** [comment]
could you please create a git to see your code?

**Comment by cmckni3** [comment]
What?

**Comment by cmckni3** [comment]
My code is still shown in the diff on this pull request.

**Comment by owen2345** [comment]
Please in the controller add except :search like this:
skip_before_filter :admin_logged_actions, except: [:index, :search]

**Comment by cmckni3** [comment]
What does that do exactly?

**Comment by owen2345** [comment]
initialize admin libraries, like sidebar menus, ...
used to skip for ajax requests

**Comment by cmckni3** [comment]
Oh ok. That's derpy. The API should really be split out.

I follow [this pattern](https://github.com/cmckni3/skillful/tree/master/app/controllers/api/v1) and version my API. I think there's some other tools that help with versioning but I just do it manually. The auto versioning just seems like too much.

**Comment by cmckni3** [comment]
Fixed in #352. Thanks!

**Pull request merged**
