### PR TITLE
Nl fixes

### PR DESCRIPTION
**Pull request by TimVNL**

### CODE REVIEW

**Comment by owen2345** [comment]
@TimVNL 
I am sorry, why pt_br was removed?

**Comment by owen2345** [comment]
Please let me know the error to fix them.

**Comment by TimVNL** [comment]
There are missing to many strings if you use the i18n gem and its very incomplete

**Comment by tachyons** [comment]
If it is incomplete , then try to complete it , removing entire language is not an option for that :-1:

**Comment by TimVNL** [comment]
@tachyons Well I can't fix the pt-br because I do not speak it I can only see thats incomplete.

**Comment by matheusvetor** [comment]
@TimVNL I can do this

**Comment by cmckni3** [comment]
Looks like it can be closed now since the fork was deleted.

**Pull request closed without merging**
