### PR TITLE
Fix comment in config/system.json to avoid Oj exception on parsing

### PR DESCRIPTION
**Pull request by texpert**
Changes:

- Move comment from outside and into the json document to avoid the following exception when trying to use the Oj gem:

```
Uncaught exception: unexpected characters after the JSON document (after ) at line 19, column 1 [parse.c:691]
```

-  Fix sample jpeg file download to fetch a file from Wikimedia instead of `camaleon.tuzitio.com` website, because the latter doesn't work and the specs are failing
-  Fix deprecation warnings about legacy_connection_handling not being supported from Rails 6.1 in the test dummy app
- Add Oj gem to the testing dummy app

### CODE REVIEW

**Review by brian-kephart — COMMENTED** [review]
I ran into this problem awhile ago when I tried to install OJ. This seems like a good change, but is it enough? My understanding is that JSON doesn't support comments, so I'm concerned that leaving a comment anywhere in this file might break another serializer even if it works with OJ. Should we try adding a dummy field instead?

```json
{
  "note": "after any change in this file, you need to restart your server to apply changes."
}
```

If you think that's a good idea, we could use something similar to preserve the other comments as well.

```json
{
  "default_template": "default",
  "default_template_comment": "default template name for new sites"
}
```

**Comment by texpert** [comment]
> 

I don't think adding dummy fields is good, because these fields will actually be data, affecting the performance and memory consumption.

Besides, comments are supported by both the `json` gem - https://github.com/flori/json/blob/823760c7dee120cbb0fd09373ba64b99455198a9/tests/json_parser_test.rb#L233, and, also, by `oj` - https://github.com/ohler55/oj/blob/620a787135ef9c1937e2265af7b11cace448038a/test/json_gem/json_parser_test.rb#L219

So, I think, other serializers, if created, will follow suit.

**Comment by brian-kephart** [comment]
I'm not really concerned about the performance impact of a JSON field, but I agree that comments are preferable if they are supported, so that sounds good to me.

I would oppose including another gem (Oj) as a test dependency, but we are dealing with a previous incompatibility so I'm okay with it in this case if no one else objects.

I think this is ready to go. 👍

**Comment by texpert** [comment]
@brian-kephart , @owen2345 , could we have a tiny release, please?!

**Comment by texpert** [comment]
> Just pushed release 2.6.4!

Thank you, @brian-kephart !

**Pull request merged**
