### PR TITLE
Add a user -> site association

### PR DESCRIPTION
**Pull request by p-decoraid**

### CODE REVIEW

**Comment by owen2345** [comment]
Hi @p-decoraid 
this will work only for non shared sites where an user belongs to a site, but with shared sites where an user belongs to many sites this will not work.
I recommend to use user.sites which is verifying the kind of sharing users.
https://github.com/Decor-Aid/camaleon-cms/blob/55758e618f664f49f554ce9a4c18601522d8f2f3/app/models/concerns/camaleon_cms/user_methods.rb#L65
Regards,

**Comment by p-decoraid** [comment]
I see, my production users are not attached to sites after all.

**Comment by owen2345** [comment]
ok, by default it is shared users between sites.
easy configuration here: https://github.com/Decor-Aid/camaleon-cms/blob/master/config/system.json#L9

**Comment by p-decoraid** [comment]
The background for this PR is I am writing some tests and trying to figure out why my admin login does not work.

**Comment by owen2345** [comment]
for that situation it will work, but you can have the same result with:
```
my_user.sites # this will return a single site like belongs_to
```

**Comment by p-decoraid** [comment]
Yep I got it, thanks.

**Pull request closed without merging**
