### PR TITLE
Migrate existing CoffeeScript files to JavaScript

### PR DESCRIPTION
**Pull request by texpert**
## Changes:

- Used decaffeinate for admin_editor migration to JS, thus creating a package.json file
- Added and configured ESLint to make the JS code cleaner
- Removed the `coffee-rails` gem

### CODE REVIEW

**Comment by texpert** [comment]
Contact Form will fail because of still used CoffeeScript. Please, review and merge there my migrating PR as well - https://github.com/owen2345/cama_contact_form/pull/50

**Review by owen2345 — APPROVED** [review]
Despite some failed tests, it LGTM

**Comment by texpert** [comment]
@owen2345, the test has passed with the master branch of the `cama_contact_form` gem. Could you, please, or @brian-kephart, publish a new RubyGems release of `cama_contact_form`, so I will be able to complete this PR?

**Review by brian-kephart — CHANGES_REQUESTED** [review]
Sorry for the delay, I've been on vacation. Thank you for doing this!

The code all looks good as-is, but if we're going to use ESLint could you please add it to the the CI?

There's currently a `lint` job to run RuboCop just for syntax errors. It probably makes the most sense to change the name of [the current job](https://github.com/owen2345/camaleon-cms/blob/master/.github/workflows/current_support.yml#L5) to `ruby-lint` or `rubocop` or something similar and make an additional lint job for JS, since the processes don't have anything to do with one another.

It might be worthwhile to add something about the linters to the contributing guidelines as well. I never did this for RuboCop because all the cops are turned off, so it's just checking for syntax errors, but if we're going to enforce an actual style it seems worth mentioning.

**Comment by owen2345** [comment]
> @owen2345, the test has passed with the master branch of the `cama_contact_form` gem. Could you, please, or @brian-kephart, publish a new RubyGems release of `cama_contact_form`, so I will be able to complete this PR?

@texpert I released `0.1.0` version.
Btw: I was on vacation too, sorry for the delay.

**Comment by texpert** [comment]
> 
> The code all looks good as-is, but if we're going to use ESLint could you please add it to the the CI?
> 

@brian-kephart, I have crafted another PR for adding ESLint to the CI, because the JS code will need some love, so there will be several changes not related to the current PR - see https://github.com/owen2345/camaleon-cms/pull/1030

So, I will merge the current one (if you approve it), and then will work on the ESLint one.

**Comment by owen2345** [comment]
@texpert since you already created another PR for @brian-kephart suggestion, I think you can merge it.

**Pull request merged**
